### ISSUE TITLE
Verification d'un seul projet ne fonctionne pas

### ISSUE THREAD

**Issue by crobix** [Mactronique/cua#8]
Lorsque l'on lance la versification d'un seul projet, l'application lance tous les projets

**Comment by macintoshplus** [comment]
La branche `feature_security_redmine_conf` contient la future version 2 de l'outil.
La configuration doit [être modifiée](https://github.com/Mactronique/cua/blob/feature_security_redmine_conf/UPGRADE_TO_2.0.md) pour être compatible.
